import playwright from '../../frontend/node_modules/@playwright/test/index.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const { test, expect } = playwright;
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

for (const viewport of [{ width: 1280, height: 720 }, { width: 390, height: 844 }]) {
  test(`checkpoint, duplicate and deleted recovery remain editable at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport);
    await page.goto('/');
    const imported = page.waitForResponse((r) => r.url().endsWith('/api/projects/import') && r.request().method() === 'POST');
    await page.getByLabel('Import video', { exact: true }).setInputFiles(path.join(root, 'tests/generated/silent.mp4'));
    const project = await (await imported).json();
    const originalName = `Versão inicial ${viewport.width} ${project.projectId.slice(0, 8)}`;
    const copyName = `${originalName} (copy)`;
    await expect(page.locator('video')).toBeVisible();
    await page.getByLabel('Project name', { exact: true }).fill(originalName);
    await page.getByLabel('Project name', { exact: true }).press('Tab');
    await page.getByRole('button', { name: 'Arrow', exact: true }).click();
    const picture = await page.getByTestId('video-picture').boundingBox();
    expect(picture).toBeTruthy();
    await page.mouse.move(picture!.x + picture!.width * .2, picture!.y + picture!.height * .3);
    await page.mouse.down();
    await page.mouse.move(picture!.x + picture!.width * .6, picture!.y + picture!.height * .6, { steps: 6 });
    await page.mouse.up();
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    const region = page.getByRole('region', { name: 'Project recovery', exact: true });
    await region.getByText('Checkpoints and copies', { exact: false }).click();
    await region.getByLabel('Checkpoint label').fill('Antes da revisão');
    await region.getByRole('button', { name: 'Save checkpoint', exact: true }).click();
    await expect(region.getByRole('button', { name: 'Restore checkpoint Antes da revisão', exact: true })).toBeVisible();
    const original = await (await page.request.get(`/api/projects/${project.projectId}`)).json();
    expect(original.annotations).toHaveLength(1);
    await page.getByRole('button', { name: 'Close projects', exact: true }).click();
    await page.getByLabel('Project name', { exact: true }).fill('Later edits');
    await page.getByLabel('Project name', { exact: true }).press('Tab');
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    await region.getByText('Checkpoints and copies', { exact: false }).click();
    page.once('dialog', (dialog) => dialog.accept());
    await region.getByRole('button', { name: 'Restore checkpoint Antes da revisão', exact: true }).click();
    await expect(page.getByLabel('Project name', { exact: true })).toHaveValue(originalName);
    await expect(page.getByTestId('save-status')).toHaveText('Saved');
    await page.reload();
    const restored = await (await page.request.get(`/api/projects/${project.projectId}`)).json();
    expect(restored.annotations).toEqual(original.annotations);
    expect(restored.revision).toBeGreaterThan(original.revision);
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    await region.getByText('Checkpoints and copies', { exact: false }).click();
    await expect(region.getByRole('button', { name: 'Restore checkpoint Before restoring Antes da revisão', exact: true })).toBeVisible();
    const copyResponse = page.waitForResponse((r) => r.url().endsWith(`/api/projects/${project.projectId}/duplicate`));
    await region.getByRole('button', { name: 'Duplicate project', exact: true }).click();
    const copy = await (await copyResponse).json();
    expect(copy.projectId).not.toBe(project.projectId);
    expect(copy.annotations[0].id).not.toBe(original.annotations[0].id);
    expect(copy.annotations[0].geometry).toEqual(original.annotations[0].geometry);
    await expect(page.getByLabel('Project name', { exact: true })).toHaveValue(copyName);
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: `Delete project ${copyName}`, exact: true }).click();
    await region.getByText('Recently deleted', { exact: false }).first().click();
    await expect(region.getByRole('button', { name: `Restore project ${copyName}`, exact: true })).toBeVisible();
    await region.getByRole('button', { name: `Restore project ${copyName}`, exact: true }).click();
    await expect(page.getByLabel('Project name', { exact: true })).toHaveValue(copyName);
    const after = await (await page.request.get(`/api/projects/${copy.projectId}`)).json();
    expect(after.annotations).toEqual(copy.annotations);
    await page.getByRole('button', { name: 'Export video', exact: true }).click();
    await page.getByRole('button', { name: 'Render MP4', exact: true }).click();
    await expect(page.getByRole('link', { name: 'Download MP4' })).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Close exports', exact: true }).click();
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: `Delete project ${copyName}`, exact: true }).click();
    await region.getByText('Recently deleted', { exact: false }).first().click();
    // Cancelling the destructive confirmation retains the project.
    page.once('dialog', (dialog) => dialog.dismiss());
    await region.getByRole('button', { name: `Permanently delete ${copyName}`, exact: true }).click();
    await expect(region.getByRole('button', { name: `Restore project ${copyName}`, exact: true })).toBeVisible();
    const removal = page.waitForResponse((r) => r.url().includes('/api/recently-deleted/') && r.request().method() === 'DELETE');
    page.once('dialog', (dialog) => dialog.accept());
    await region.getByRole('button', { name: `Permanently delete ${copyName}`, exact: true }).click();
    expect((await removal).status()).toBe(204);
    const remaining = await (await page.request.get('/api/recently-deleted')).json();
    expect(remaining.some((item: {projectId: string}) => item.projectId === copy.projectId)).toBe(false);
    await expect(region.getByRole('button', {name: `Restore project ${copyName}`, exact: true})).toHaveCount(0);
    await page.reload();
    const reopenedTrash = await (await page.request.get('/api/recently-deleted')).json();
    expect(reopenedTrash.some((item: {projectId: string}) => item.projectId === copy.projectId)).toBe(false);
    expect((await page.request.get(`/api/projects/${project.projectId}`)).ok()).toBeTruthy();
    expect((await page.request.get(`/api/projects/${copy.projectId}`)).status()).toBe(404);
    const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
    expect(horizontalOverflow).toBe(false);
  });
}
